name: toc-app-prod

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: toc-api
    build:
      context: .
      target: production
    env_file:
      - .env
    restart: always
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_prod_data:
  django_static:
  django_media: