# Generated by Django 6.1 on 2026-08-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="login_email",
            field=models.EmailField(
                default="temp@example.com", max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="oauth_token",
            field=models.CharField(
                default="temp_oauth_token", max_length=255, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
