# Generated by Django 6.1 on 2026-08-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="oauth_token",
            new_name="oauth_id",
        ),
    ]
