# Generated by Django 6.1 on 2026-08-18 17:58

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_oauth_token_user_oauth_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="oauth_id",
        ),
        migrations.AddField(
            model_name="user",
            name="oauth_token",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
    ]
