# Generated by Django 6.1 on 2026-08-18 18:01

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('masking_data', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='maskingdata',
            name='address',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='maskingdata',
            name='dob',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='maskingdata',
            name='email',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='maskingdata',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
