# Generated by Django 6.1 on 2026-08-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('number', models.TextField()),
                ('masked_number', models.TextField()),
                (
                    'status',
                    models.CharField(
                        choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')],
                        default='ACTIVE',
                        max_length=20,
                    ),
                ),
            ],
            options={'db_table': 'credit_cards'},
        )
    ]
