# Generated by Django 6.1 on 2026-08-18 18:01

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('credit_cards', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        )
    ]
